### PR TITLE
Feature/pandas agent

### PR DESCRIPTION
**Pull request by amjadraza**
Created a Streamlit app to Chat with Pandas DataFrames.

### CODE REVIEW

**Comment by amjadraza** [comment]
@sfc-gh-jcarroll Please deploy the app on Public Streamlit Cloud, if needed. 

Thanks

**Comment by sfc-gh-jcarroll** [comment]
Nice! I need to update a couple things on this PR to make it work better in Streamlit Community Cloud, I will get it up in the next day or two 😄 Thanks for the contribution!!

**Comment by amjadraza** [comment]
@sfc-gh-jcarroll no worries. Take your time. Ping me if you have any concerns/clarifications.

**Comment by sfc-gh-jcarroll** [comment]
This is great! I cleaned up a couple things to make it easier to deploy on Cloud and be consistent with the rest of the apps. I'm going to merge and deploy, feel free to open another PR if you want to do further improvements or discuss any of the changes.

Thank you!!

**Comment by amjadraza** [comment]
@sfc-gh-jcarroll Thanks.

**Pull request merged**
