### PR TITLE
Fix bug with api key getting cached, other small cleanups

### PR DESCRIPTION
**Pull request by sfc-gh-jcarroll**
Found a bug in chat-with-sql and chat-with-documents examples where an OpenAI API Key could be cached unexpectedly and cause various problems. This PR fixes the bug. Also cleaned up a couple other small things.

### CODE REVIEW

**Comment by sfc-gh-jcarroll** [comment]
FYI @Muhtasham @shashankdeshpande on these fixes

**Comment by shashankdeshpande** [comment]
@sfc-gh-jcarroll Thanks for letting me know about the issue. Just curious, is it related  to `st.cache_resource`? Should the key configuration be placed outside cache?

**Comment by sfc-gh-jcarroll** [comment]
Yes the cached function will return the same object every time if the input is the same. so api key was being set in the first execution and then returned when the files were the same / db uri was the same (cached function arg) even if you change the key in the UI.

Another way to solve would have been adding the api_key as an argument to the cached function but I decided this approach was cleaner since the llm object construction is very fast (no noticeable penalty to re-create it on every rerun)

**Comment by shashankdeshpande** [comment]
@sfc-gh-jcarroll Got it, thanks for clarification!

**Pull request merged**
